version: '3'

services:
    web:
        build: .
        container_name: web
        environment:
          SECRET_KEY: ${SECRET_KEY}
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
